version: 2
sources:
    - name: datafeed_shared_schema
      database: "{{('db')}}"
      schema: sh
      tables:
        - name: orders
        - name: raw_payments
        - name: customer
        - name: suppies